app/companys/urls.py
from django.urls import path

from companys.views import crawling

app_name = 'companys'

urlpatterns = [
    path('crawling/', crawling, name='crawling')
]

app/config/urls.py
from django.contrib import admin
from django.urls import path, include

from config.views import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('members/', include('members.urls')),
    path('companys/', include('companys.urls')),
    path('mail/', include('mail.urls')),
]

app/mail/urls.py
from django.urls import path

from mail.views import mail

urlpatterns = [
    path('', mail, name='mail'),
]

app/members/urls.py
from django.conf.urls import url
from django.urls import path, include

from members.views import login_view, user_setting_view, logout_view, send_email, withdrawal

app_name = 'members'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('user-setting/', user_setting_view, name='user-setting'),
    path('send-email/', send_email, name='send-email'),
    path('withdrawal/', withdrawal, name='withdrawal'),
]

app/companys/models.py
from django.db import models


class Company(models.Model):
    name = models.CharField(max_length=20)
    address = models.TextField()

class Info(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    desc = models.TextField()
    price = models.CharField(max_length=20, null=True)
    soldout = models.BooleanField(default=True)

# test를 위한 models 생성
class Mask_Info(models.Model):
    name = models.CharField(max_length=20)
    desc = models.TextField()
    price = models.CharField(max_length=20, null=True)
    soldout = models.BooleanField(default=True)

app/members/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    send_email = models.BooleanField(default=True)
    authorization = models.BooleanField(default=False)

app/companys/views.py
import json, os, re, requests
from bs4 import BeautifulSoup
import urllib.request

from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string

from companys.models import Mask_Info

def crawling():
    # Mask_Info.objects.all().delete()

    url = 'http://www.welkeepsmall.com/shop/shopbrandCA.html?type=X&xcode=023'
    html = urllib.request.urlopen(url).read()
    soup = BeautifulSoup(html, 'html.parser')

    mask_list = []

    mask_all_info = soup.select(".info")
    # print(mask_all_info)

    mask_text_list = []
    for mask in mask_all_info:
        mask_text_list.append(mask.get_text())

    list_len = len(mask_text_list)

    for mask in range(list_len):
        mask_list.append(mask_text_list[mask].split('\n'))

    for mask in mask_list:
        del mask[0]

    # 구매 가능한 마스크
    buy_mask = []

    for num in range(list_len):
        name = (mask_list[num])[0]
        desc = (mask_list[num])[1]
        soldout = (True if (mask_list[num])[2] == "SOLD OUT" else False)
        price = (mask_list[num])[3]

        Mask_Info.objects.get_or_create(name=name, desc=desc, price=price, soldout=soldout)

        buy_mask_list = Mask_Info.objects.filter(soldout=0).values('name')

    for buy in buy_mask_list:
        buy_mask.append(buy['name'])

    print('buy_mask', buy_mask)
    print('if buy_mask != []', buy_mask != [])
    print('if buy_mask == []', buy_mask == [])
    print('buy_mask str', str(buy_mask))
    print('buy_mask str type', type(str(buy_mask)))

    if buy_mask != []:
        print('메일 발송')
        # send_email('wtw9611@gmail.com', str(buy_mask))
        # send_mail(
        #     '[안내 메일]웰킵스 구매 가능!',
        #     'buy_mask 마스크 구매가능',
        #     'welkeeps.service@gmail.com',
        #     ['wtw9611@gmail.com'],
        #     fail_silently=False,
        # )


# def send_email(email, buy_mask):
#     subject = '[안내] 웰킵스 마스크 구매 가능!'
#     from_email = 'welkeeps.service@gmail.com'
#     to = 'wtw9611@gmail.com'
#     text_content = '마스크 구매 가능합니다.'
#     html_content = '<p> <strong>웰킵스 마스크 구매 가능 안내</strong> 메일입니다.</p>' \
#                    '<small style="font-color:gray">이 메일은 웰킵스 안내 서비스에 가입하신 고객님께 보내드리는 메일입니다.</small>' \
#             msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
#     msg.attach_alternative(html_content, "text/html")
#     msg.send()
#

crawling()

app/config/views.py
from django.contrib.auth import login
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from members.models import User


def index(request):
    if request.method == 'GET':
        return render(request, 'index.html')

    if request.method == 'POST':
        email = request.POST['username']
        username = request.POST['username']
        password = request.POST['password']

        if User.objects.filter(email=email).exists():
            messages.add_message(request, messages.ERROR, '앗! 이미 사용중인 email입니다.')
            return redirect('index')

        user = User.objects.create_user(
            password=password,
            username=username,
            email=email,
            send_email=True
        )

        if user is not None:
            login(request, user)
            return redirect('members:user-setting')

        return redirect('members:login')

app/members/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.http import HttpResponse
from django.shortcuts import render, redirect

User = get_user_model()


def login_view(request):
    if request.method == 'POST':
        # email = request.POST['email']
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('members:user-setting')

        else:
            messages.add_message(request, messages.ERROR, '가입되지 않은 정보입니다. 다시 확인 후 입력해주세요.')
            return render(request, 'members/login.html')

    else:
        return render(request, 'members/login.html')


def user_setting_view(request):
    if str(request.user) != 'AnonymousUser':
        return render(request, 'members/user_setting.html')
    return redirect('members:login')


def logout_view(request):
    logout(request)
    return redirect('members:login')


# 수신 상태 변경
def send_email(request):
    email = request.user
    user = User.objects.get(email=email)
    user.send_email = False if user.send_email == True else True
    user.save()
    return redirect('members:user-setting')


# 회원탈퇴 처리
def withdrawal(request):
    # if request.method == 'POST':
    print('회원탈퇴 함수 접근')
    request.user.delete()
    messages.add_message(request, messages.ERROR, '회원탈퇴가 완료되었습니다.')
    return redirect('index')
    # else: return redirect('members:user-setting')

app/templates/index.html
{% load static %}

<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.css' %}">
    <title>웰킵스 마스크 메일링 서비스</title>
</head>
<body>

<div class="main">
    <div class="row bg-dark w-100 h-100 position-absolute" style="background-color:black;">
        <image class="position-absolute h-100"
               src="https://images.unsplash.com/photo-1580094687196-cbc2bdab67e4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80"
               style="right:0px;"></image>
    </div>
    <div class="container h-100">
        <div class="row h-100">
            <div class="col-12 my-auto">
                <div class="main-content text-white py-5 py-md-0">
                    <h1 class="mb-3">웰킵스 마스크 메일링 서비스 신청하기</h1>
                    <p class="mb-5">매일 판매하고 있는 웰킵스 마스크 사이트에서
                        <strong>마스크가 구매가능할 때</strong> 메일로 알림을 드려요.</p>
                    <p class="mb-2 text-info small">이메일과 비밀번호 입력 시 메일링 서비스에 동의한 것으로 간주되어 메일이 발송됩니다.</p>
                    <form method="POST" class="w-50">
                        {% csrf_token %}
                        <input type="email" name="username" class="form-control mb-1" placeholder="실 사용중인 이메일을 입력하세요.">
                        <input type="password" name="password" class="form-control mb-2" placeholder="사용할 비밀번호를 입력하세요.">
                        {% if messages %}
                        {% for message in messages %}
                        <p class="text-warning">{{ message.message }}</p>
                        {% endfor %}
                        {% endif %}
                        <button class="btn btn-warning" data-toggle="modal" data-target="#exampleModal" type="submit">
                            메일링 서비스 신청하기
                        </button>
                    </form>

                    <div>
                        <div>
                            메일링 서비스를 신청한 정보를 수정하고 싶은 경우 로그인하세요.
                            <a href="{% url 'members:login' %}" class="btn btn-outline-light" role="button"
                               aria-pressed="true">로그인하기</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

app/templates/members/login.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.css' %}">
    <link rel="script" href="{% static 'bootstrap/bootstrap.js' %}">
    <title>웰킵스 마스크 메일링 서비스</title>
</head>
<body>

<div class="main">
    <div class="row bg-dark w-100 h-100 position-absolute" style="background-color:black;">
        <image class="position-absolute h-100"
               src="https://images.unsplash.com/photo-1580094687196-cbc2bdab67e4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80"
               style="right:0px;"></image>
    </div>
    <div class="container h-100">
        <div class="row h-100">
            <div class="col-12 my-auto">
                <div class="main-content text-white py-5 py-md-0">
                    <h1 class="mb-3">웰킵스 마스크 메일링 서비스 로그인</h1>
                    <p class="mb-5">매일 판매하고 있는 웰킵스 마스크 사이트에서
                        <strong>마스크가 구매가능할 때</strong> 메일로 알림을 드려요.</p>
                    <form method="POST" class="w-50">
                        {% csrf_token %}
                        <input type="email" class="form-control mb-1" placeholder="이메일을 입력하세요." name="username">
                        <input type="password" class="form-control mb-2" placeholder="비밀번호를 입력하세요." name="password">
                        {% if messages %}
                        {% for message in messages %}
                        <p class="text-warning">{{ message.message }}</p>
                        {% endfor %}
                        {% endif %}
                        <button class="btn btn-warning" type="submit">로그인하기</button>
                    </form>
                    <div>
                        메일링 서비스를 가입하고 싶으신가요?
                        <a href="{% url 'index' %}" class="btn btn-outline-light" role="button"
                           aria-pressed="true">가입하기</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

app/templates/members/user_setting.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.css' %}">
    <link rel="script" href="{% static 'bootstrap/bootstrap.js' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.js"></script>
    <script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
    <title>웰킵스 마스크 메일링 서비스</title>
</head>
<body>

<div class="main">
    <div class="row bg-dark w-100 h-100 position-absolute" style="background-color:black;">
        <image class="position-absolute h-100"
               src="https://images.unsplash.com/photo-1580094687196-cbc2bdab67e4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80"
               style="right:0px;"></image>
    </div>
    <div class="container h-100">
        <div class="row h-100">
            <div class="col-12 my-auto">
                <div class="main-content text-white py-5 py-md-0">
                    <h1 class="mb-3">User Setting</h1>
                    <p style="font-size:1.3rem;">안녕하세요, <strong>{{ request.user }}</strong>님</p>
                    <p>현재 회원님께서는 웰킵스 이메일
                        {% if request.user.send_email %}<strong class="text-success"> 수신동의 </strong> 상태입니다. <br>
                        구매 가능한 시점에 회원님의 이메일로 자동 발송됩니다.
                        {% else %} <strong class="text-warning"> 수신미동의 </strong> 상태입니다.<br>
                        하단 <i>'수신 상태 변경하기'</i> 버튼을 클릭해 수신동의 상태로 변경하시면 <br>
                        구매 가능한 시점을 이메일로 받아보실 수 있습니다.
                        {% endif %}
                    </p>

                    <a href="{% url 'members:send-email' %}" class="btn btn-primary" type="button">수신 상태 변경하기</a>
                    <a href="{% url 'members:logout'%}" class="btn btn-secondary" type="button">로그아웃</a>
                    <a href="{% url 'members:withdrawal' %}" class="btn btn-outline-secondary" type="button">회원탈퇴하기</a>
<!--                    <button class="btn btn-outline-secondary" type="button"-->
<!--                            data-toggle="modal" data-target="#myModal">회원탈퇴하기-->
<!--                    </button>-->

                </div>
            </div>
        </div>
    </div>
</div>

<!-- 팝업 -->

<!--<div class="container popup">-->
<!--    <div class="modal fade" id="myModal" role="dialog">-->
<!--        <div class="modal-dialog">-->
<!--            <div class="modal-content">-->
<!--                <div class="modal-header">-->
<!--                    <h4 class="modal-title">정말 회원을 탈퇴하시겠습니까?</h4>-->
<!--                    <button type="button" class="close" data-dismiss="modal">&times;</button>-->
<!--                </div>-->
<!--                <div class="modal-body">-->
<!--                    <p>탈퇴를 원하시면 하단 <strong>탈퇴</strong> 버튼을 클릭해주세요.</p>-->
<!--                    <p>원치 않으시면 <strong>취소</strong> 버튼을 클릭하세요.</p>-->
<!--                </div>-->
<!--                <div class="modal-footer">-->
<!--                    <button type="button" class="withdrawal btn btn-danger" data-dismiss="modal">탈퇴</button>-->
<!--                    <button type="button" class="btn btn-info" data-dismiss="modal">취소</button>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->


<!--<script type="text/javascript">-->

<!--    const $main = document.querySelector('.main')-->

<!--    $main.addEventListener('click', function(e){-->
<!--        $withdrawal= $main.nextElementSibling.childNodes[1].childNodes[1].childNodes[1].childNodes[5].childNodes[1];-->
<!--        $withdrawal.addEventListener('click', function(e){-->
<!--            console.log('클릭');-->
<!--            axios.post('{% url 'members:withdrawal' %}')-->
<!--                .then(function(response){-->
<!--                    console.log(response)-->
<!--                    console.log('post')-->
<!--                })-->
<!--        })-->
<!--    })-->

<!--</script>-->
</body>
</html>